# Generated by Django 5.2.9 on 2026-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحملة')),
                ('platform', models.CharField(choices=[('X', 'X (Twitter)'), ('TikTok', 'TikTok'), ('Snapchat', 'Snapchat')], max_length=20, verbose_name='المنصة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('reach', models.PositiveIntegerField(default=0, verbose_name='عدد الوصول (Reach)')),
                ('engagement', models.PositiveIntegerField(default=0, verbose_name='عدد التفاعل (Engagement)')),
                ('media_theory', models.CharField(max_length=255, verbose_name='النظرية الإعلامية')),
                ('scientific_evaluation', models.TextField(verbose_name='التقييم العلمي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'حملة',
                'verbose_name_plural': 'الحملات',
                'ordering': ['-created_at'],
            },
        ),
    ]
