# Generated by Django 6.0.4 on 2026-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('Awareness', 'توعوية'), ('Commercial', 'تجارية'), ('National', 'وطنية'), ('Sports', 'رياضية')], default='Awareness', max_length=50, verbose_name='نوع الحملة'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='platform',
            field=models.CharField(choices=[('X', 'X (Twitter)'), ('TikTok', 'TikTok'), ('Snapchat', 'Snapchat'), ('Instagram', 'Instagram')], max_length=20, verbose_name='المنصة'),
        ),
    ]
