# Generated by Django 6.0.4 on 2026-05-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_category_alter_campaign_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='كلمة البحث')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign', verbose_name='الحملة المرتبطة')),
            ],
            options={
                'verbose_name': 'تاريخ البحث',
                'verbose_name_plural': 'تاريخ البحث',
                'unique_together': {('query',)},
            },
        ),
    ]
