# Generated by Django 6.0.4 on 2026-05-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_usersearchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersearchhistory',
            old_name='query',
            new_name='search_query',
        ),
        migrations.AlterUniqueTogether(
            name='usersearchhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersearchhistory',
            name='platform',
            field=models.CharField(default='X', max_length=20, verbose_name='المنصة المختارة'),
        ),
        migrations.AlterUniqueTogether(
            name='usersearchhistory',
            unique_together={('search_query', 'platform')},
        ),
    ]
