# Generated by Django 6.0.4 on 2026-05-02 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_query_usersearchhistory_search_query_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersearchhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersearchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterUniqueTogether(
            name='usersearchhistory',
            unique_together={('user', 'search_query', 'platform')},
        ),
    ]
