# Generated by Django 6.0.4 on 2026-05-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_usersearchhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='engagement_rate',
            field=models.FloatField(default=0.0, verbose_name='معدل التأثير'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='success_rate',
            field=models.IntegerField(default=0, verbose_name='درجة النجاح'),
        ),
    ]
