# Generated by Django 6.0.4 on 2026-05-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_engagement_rate_campaign_success_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='engagement_rate',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='success_rate',
        ),
    ]
